### ISSUE TITLE
Improve compile times

### ISSUE THREAD

**Issue by mre** [tinysearch/tinysearch#12]
At the moment, it takes ages to generate the Wasm binary.
That's because we download an entire crate and compile it whenever we run `tinysearch corpus.json`. Maybe anyone has an idea on how to improve that?

**Comment by CephalonRho** [comment]
Hey, I made a pull request to address this issue. (https://github.com/mre/tinysearch/pull/13)
The idea is to keep the intermediate build artifacts in $PWD/tinysearch_build instead of leaving them in the temporary download directory, allowing cargo to find them on subsequent builds.
There is still room for improvement as the download could be cached too, but the wasm-pack build time should be almost as good as it gets for a release build now.

**Comment by mre** [comment]
That was fast. Thanks for the fix. The results are quite astonishing (1m17s to 6s).
I'll keep this open for further improvements, but we're off to a great start.

**Comment by mre** [comment]
Two more ideas:
* [ ] Remove unused dependencies with [cargo-udeps](https://github.com/est31/cargo-udeps)
* [ ] Evaluate [miniserde](https://github.com/dtolnay/miniserde) for serialization.

**Comment by mre** [comment]
Have to try https://endler.dev/2020/rust-compile-times/

**Comment by mre** [comment]
After the recent updates compile times should no longer be a big problem. I see around 20-25 seconds on a fresh build. 
This is thanks to a reduction in dependencies, less usage of macros, and wasm-pack and Rust compiler improvements. 😊
