### ISSUE TITLE
Make installation easier

### ISSUE THREAD

**Issue by mre** [tinysearch/tinysearch#15]
Would be great if we could make installation work without `cargo`.
Distributions, roughly ordered by complexity:

* [x] [binary releases](https://github.com/mre/tinysearch/releases) on Github
* [ ] homebrew formula
* [ ] npm package

Feel free to pick any task from the list.

**Comment by mre** [comment]
Superseded by #69.

**Comment by notpushkin** [comment]
Now that #69 is fixed, is there any chance to make a binary release? Or is there some other obstacle?

P. S. thanks for such a neat project!

**Comment by mre** [comment]
Oh yeah, absolutely. I don't think there should be any other obstacles. 
We did something similar for hyperjson once. Here's the code:
https://github.com/mre/hyperjson/blob/master/.github/workflows/ci.yml#L161-L167

Wanna take that one @notpushkin?

**Comment by mre** [comment]
Reopening this

**Comment by kvz** [comment]
Not having a binary release is causing some friction when onboarding if you do not have rust experience or a rust dev env set up. If the goal is adoption, this would be a good one to tackle imho.

**Comment by notpushkin** [comment]
Looks like we have [CI up and running](https://github.com/tinysearch/tinysearch/actions), just no nightly releases are being uploaded. Also there's the [tinysearch/cli](https://hub.docker.com/r/tinysearch/cli) image on Docker Hub, but it's outdated because the Docker Hub fails to build the image for some reason:

![image](https://user-images.githubusercontent.com/1298948/103827701-a4787a00-508a-11eb-9feb-9389c105d2c1.png)

If you're okay with running a slightly out-of-date version (which [uses slightly older dependencies and doesn't include some fixes](https://github.com/tinysearch/tinysearch/compare/8b87a55534a260f2be29b430229c24ee391783c0...master)), `docker run tinysearch/cli` should work just fine. :sparkles:

**Comment by mre** [comment]
Old issue. We got binary releases now, which is "good enough" for the moment. Homebrew and NPM would be more work, but maybe we won't need those? Closing to keep the issue tracker clean.
