### ISSUE TITLE
Failing to find Cargo.toml in temp directory?

### ISSUE THREAD

**Issue by ms-ati** [tinysearch/tinysearch#165]
After struggling mightily with tinysearch installed via Homebrew and direct downloads, this one was installed via `cargo install tinysearch`, `cargo install wasm-pack`

Help please, I am still stuck :(

Why is `tinysearch`'s invocation of `wasm-pack` looking for a `Cargo.toml` file in the temp directory it created?

```
tinysearch --optimize --path static public/data_tinysearch/index.html
Unpacking tinysearch WASM engine into temporary directory "/var/folders/nx/7ys_xr014yg41_mw1zn_wvb00000gn/T/.tmpMxhsOO"
Starting unpack
Copying index into crate
Compiling WASM module using wasm-pack
Error: crate directory is missing a `Cargo.toml` file; is `/var/folders/nx/7ys_xr014yg41_mw1zn_wvb00000gn/T/.tmpMxhsOO/engine` the wrong directory?
Error: failed to execute "wasm-pack" "build" "/var/folders/nx/7ys_xr014yg41_mw1zn_wvb00000gn/T/.tmpMxhsOO/engine" "--target" "web" "--release" "--out-dir" "/Users/name/blog/static"
status: exit status: 1
```

**Comment by mre** [comment]
The engine code gets extracted into a temp dir. It's just another cargo project that gets compiled with wasm-pack. That's why the `Cargo.toml` is needed. Looks like the `Cargo.toml` isn't properly included in the binary for some reason.

https://github.com/tinysearch/tinysearch/blob/14ef25ca7ec04566f259cc1baabd7e220dd4cfe7/bin/src/main.rs#L18-L20

I thought we fixed that already.

**Comment by ms-ati** [comment]
Hi @mre thanks for all this work. Would you be interested if I were to contribute Github Action tests which would provide regression testing against these issues, by fully building and running and verifying on each PR? Apologies if this exists but is in some way not yet sufficient coverage, I’d also be happy to help address in that case as well.

**Comment by mre** [comment]
Yeah that would be nice. Sorry for the limited availability at the moment, but your help would be much appreciated.
@Jieiku fyi. Not sure if you could look into that.
The Github action (https://github.com/leonhfr/tinysearch-action) is maintained by @leonhfr.

**Comment by ASMfreaK** [comment]
I have the same issue. I think it is caused by `cargo install tinysearch` not including the right assets (needed for `engine.rs`). The issue is cause by these lines:

https://github.com/tinysearch/tinysearch/blob/10c060bb5a496b699be33ad3108e1cb36760d308/bin/build.rs#L7-L8

It is also caused by cargo install getting sources not from github, but from crates.io. Here is the listing from cargo's build folder for tinysearch:
```
$ tree ~/.cargo/registry/src/github.com-1ecc6299db9ec823/tinysearch-0.7.0/
~/.cargo/registry/src/github.com-1ecc6299db9ec823/tinysearch-0.7.0/
├── assets
│   ├── demo.html
│   └── stopwords
├── build.rs
├── Cargo.lock
├── Cargo.toml
├── Cargo.toml.orig
└── src
    ├── index.rs
    ├── main.rs
    └── storage.rs

2 directories, 9 files
```

For some reason the lines mentioned previously were not failing the build script and therefore the build.

**Comment by ASMfreaK** [comment]
The thing that worked for me:

1. Clone tinysearch repo somewhere:
```
git clone https://github.com/tinysearch/tinysearch.git
```
2. Go to `bin`  inside repo:
```
cd tinysearch/bin
```
3. Run cargo install from it:
```
cargo install --path .
```

**Comment by mre** [comment]
@ASMfreaK if you can provide a fix for that and create a pull request I'd be extremely thankful. Thanks for the investigation! 😊

**Comment by davehorner** [comment]
std::env::var is correct in build scripts.

**Comment by ASMfreaK** [comment]
I'll make a PR with solution and some other improvements

**Comment by Jieiku** [comment]
This is exactly the problem I get if I try to install via cargo, but installing and building from git seems to work fine.

see here: https://github.com/tinysearch/tinysearch/issues/151#issuecomment-1507465942

and here: https://github.com/tinysearch/tinysearch/issues/151#issuecomment-1501205986

**Comment by mre** [comment]
This is resolved now.

The reason why it broke was a limitation by cargo: it does not allow including one crate inside another one. This is done to avoid unwanted complexity and is a sane default. In our case, however, it leads to the situation that the engine crate was missing from the tinysearch crate on crates.io.
See also https://github.com/tinysearch/tinysearch/issues/170#issuecomment-1650709333.

The latest tinysearch 0.8.2 fixes this issue. Apologies for the long delay to produce a fix.
